# fly.toml file generated for proud-sound-5508 on 2023-04-18T19:50:31-05:00

app = "proud-sound-5508"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "dfw"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
